### ISSUE TITLE
Feedback loop to automatically react in case of issue

### ISSUE THREAD

**Issue by frederic-gilles** [AmadeusITGroup/kanary#40]
Hello,

Why not getting inspired by A/B testing methodology ?
If on new nodes, we detect a degradation of performance, response time... (any KPI that we may build based on time series data in Promotheus), an automatic process may reduce the traffic (if we are reaching some thresholds defined in the kanary config.).
In this case, the kanary loads will help us to ensure a better stability, to comply with our SLA...

Thanks and regards,
Frederic

**Comment by dbenque** [comment]
Hi Frederic,
I think that would not be aligned with the initial intention: a canary test campaign is run to validate that new version (of the binary or the config) does not break the system.

Reminder:
- Canary purpose is to validate that something is ok/ko
- A/B testing is to compare (technical KPI (cpu consumption) or functional KPI (user adoption)) knowing that A and B are valid (you have already done a canary on A and B potentially)

Back to your proposal, if we tweak (reduce) that traffic sent to the kanary based on a measured degradation of service due to the canary, we would completely defeat the initial purpose. I mean the campaign would artificially reduce the pressure on the canary instance, leading potentially to a validation of this one, while under real condition, it is not able to sustain the load.
To maintain the stability of the system, as soon as the canary instance breaks the threshold, the canary is declared 'dead', the test campaign stops and the instance is removed from live traffic.

Regards,
David

**Comment by frederic-gilles** [comment]
Hello,
If you could declare the new version as 'dead' depending on various criteria defined above (_degradation of performance, response time... - any KPI that we may build based on time series data in Promotheus_), it will match the idea.
I was just referring to A/B testing as it is just similar in the principle (defining an action depending on metrics measured on 2 different models).
Canary load is usual/standard..., but a canary load with enough logic to protect the SLA... is less frequent.
Thanks and regards,
Frederic

**Comment by dbenque** [comment]
Yes you can declare the canary dead based on any KPI. You can even combine several KPIs. So you can protect your SLA. Still depending the type of traffic shape you select(with live traffic) the user may be affected for couple of transactions over few seconds, the time for the system to react and kill the canary.
